### ISSUE TITLE
Unsound use of `from_utf8_unchecked`.

### ISSUE THREAD

**Issue by CodesInChaos** [dnsl48/yamlette#4]
The `Model.decode` function is not marked `unsafe`, but it relies on an `&[u8]` parameter being valid UTF-8. At minimum you should mark `decode` unsafe and review all its callers. Though it might be a good idea to change the design to reduce the amount of code exposed to this unsafety.

**Comment by dnsl48** [comment]
Hi @CodesInChaos, I agree that it looks a bit obcure and may be refactored in a cleaner way.
Nonetheless, the idea is that the library itself is encoding agnostic as long as the ASCII subset of the control characters is utilised.
Regarding the unsafe decode, the idea is that it is safe. The current design implies everything incoming to `decode` to be converted from a `String` to `&[u8]` before, which makes it virtually safe to encode back to `String`. So I have simply been using `from_utf8_unchecked` to make it faster with that only assumption in mind. If the assumption breaks, it's necessary to use only safe methods instead.

**Comment by CodesInChaos** [comment]
The problem is that this function is not marked safe and yet makes unsafe assumptions about its arguments, which is made worse by it being a public function that can be called from outside your crate.

The minimal fix would be marking it `unsafe` and adding `unsafe` blocks in all callers.

Though as far as I can tell, if `decode` and `try_decodable_models` were changed to take `&str`, you could use `from_utf8_unchecked` in a single place, `Savant.read_scalar` to assert `chunk` is valid UTF-8 (assuming chunk boundaries align with UTF-8 boundaries).

**Comment by dnsl48** [comment]
Thank you for looking into it. I would rather inclined to say the minimal and easiest fix would be using `from_utf8` instead of `from_utf8_unchecked` and not changing the trait definition with dozens of struct definitions.
Regarding using `&str` I think that's a good idea as well. Initially the idea was to have the library encoding agnostic and working with simply byte streams. However, that's already not too efficient when it comes to whide char encodings (UTF-16 or UTF-32 even). So, perhaps we could do a single operation of convertion into UTF8 once in a single place before we giving the data to the library and then all the library APIs could be rewritten to use `&str` instead of `&[u8]`. Though, that would require a bit more work than simply replace `from_utf8_unchecked` to `from_utf8`.
I think I will give it a go for the next version of the library. In the short term, as a fix I guess we could simply remove the unsafe methods usage and replace them with safe `from_utf8` to make it comply with the Rust `safe-unsafe` semantics.
PRs are welcome in any way :) Though, I'll try to find some time for that later this week.
